version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Sobrescribe la variable de entorno para apuntar al servicio de mongo en la red de docker
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      # Monta el directorio de la app para hot-reloading durante el desarrollo
      - ./app:/app/app
    # Sobrescribe el comando por defecto para habilitar --reload para el desarrollo
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
